### ISSUE TITLE
About T3

### ISSUE THREAD

**Issue by sun-0704** [mqalkhatib/SDF2Net#1]
Hi authors,
I'm interested in your work, I have questions about the dataset used in the article. Could you tell me how to get the "T3" folder when change similar datasets like PolSF, Thanks a lot.

Best wishes!

**Comment by mqalkhatib** [comment]
Hi, Getting the datasets was the hardest challenge when I started the project. Initially, the files I obtained were in .stk format (for San Francisco, I used this link to get the SF AIRSAR along with the ground truth: https://github.com/liuxuvip/PolSF?tab=readme-ov-file).
to get the T3 Folder (The coherency data), I used PolSAR Pro to extract the .bin Files (I used the attached document to do that)
[1_Getting_started_with_PolSARpro.pdf](https://github.com/mqalkhatib/SDF2Net/files/14423634/1_Getting_started_with_PolSARpro.pdf)

Let me know if my answer is sufficient :) I'm more than happy to collaborate. feel free to contact me on mqalkhatib@ieee.org

Regards,
Mohammed Q. Alkhatib

**Comment by sun-0704** [comment]
Thank you very much for your answer, I have successfully used PolSARPro to get T3 matrix with your help.
Best wishes!




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mqalkhatib/SDF2Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 凌晨2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mqalkhatib/SDF2Net] About T3 (Issue #1)





 
Hi, Getting the datasets was the hardest challenge when I started the project. Initially, the files I obtained were in .stk format (for San Francisco, I used this link to get the SF AIRSAR: https://github.com/liuxuvip/PolSF?tab=readme-ov-file).
 to get the T3 Folder (The coherency data), I used PolSAR Pro to extract the .bin Files (I used the attached document to do that)
 1_Getting_started_with_PolSARpro.pdf
 
I also had to request the Class Maps from another researcher to validate my model.
 
Let me know if my answer is sufficient :) I'm more than happy to collaborate.
 
Regards,
 Mohammed Q. Alkhatib
